### ISSUE TITLE
False positive virus

### ISSUE THREAD

**Issue by giodelgado** [vincelwt/harmony#19] opened 2016-09-08 04:59 UTC
Norton deleted the file after downloading, Virustotal.com detected this as well:

https://www.virustotal.com/en/file/3782611aad4faa7f7f4db0785302d0ebe6e628da534c4864930146eb185ef0ca/analysis/

?

**Comment by vincelwt** [comment] 2016-09-08 05:21
That's strange, 
Harmony is builded for Windows with electron-builder (open-source). 
Maybe an issue from their side?

**Comment by vincelwt** [comment] 2016-09-08 14:19
It seems to be caused by Asar packaging, see:
http://electron.atom.io/docs/tutorial/application-packaging/

Will try to disable it to see if it changes anything

**Comment by vincelwt** [comment] 2016-09-08 14:54
Still detected:
https://www.virustotal.com/en/file/bf1d3cd11f68550d3c2bdf138ab5fc440c07850ef08987c08631ba8fa832ea53/analysis/1473345665/

Closing until news

**Closed by vincelwt** 2016-09-08 14:54 UTC
Labels: bug
