### ISSUE TITLE
Spotify Discover Weekly

### ISSUE THREAD

**Issue by patricklibert** [vincelwt/harmony#204] opened 2018-03-06 19:59 UTC
Hi there,

I'm running ubuntu 16.04.4.
Should the playlist 'Discover Weekly' be updated every week?

Since I use the program, the Discover weekly hasn't changed the playlist...

**Comment by vincelwt** [comment] 2018-03-07 10:00
Hi,

By any chance, did you try refreshing your library? 
The little refresh icon in the bottom left corner.

**Comment by patricklibert** [comment] 2018-03-07 12:02
Hi,

Of course I tried refreshing the library, that doesn't help.

**Comment by vincelwt** [comment] 2018-03-07 20:44
Must be a bug then. Could you share a screenshot of the console just after refreshing the library?
You can open the console with Ctrl+alt+i, "console" tab

**Comment by patricklibert** [comment] 2018-03-07 21:15
So I start Harmony, local files are loaded and spotify is loaded except the
discover list is always the same. No errors.
Then I start console and refresh the library, the local files seems good
but then it seems to crash....

See screenshot

**Comment by patricklibert** [comment] 2018-03-07 21:22
It's the same with spotify webplayer, probably I'm doing something wrong in
spotify.
I don't think this is a bug in Harmony

**Comment by patricklibert** [comment] 2018-03-07 21:30
I listen to the music with spotify webplayer, will let you know if it
updates next monday.

**Comment by vincelwt** [comment] 2018-03-07 21:43
Yes, if it's the same in the webplayer then it's definitely not a bug with Harmony. Harmony should have the same playlists as spotify's web player (or whatever other player). 

I'll close this. Feel free to alert if it updates on Spotify's side but not Harmony's.

**Closed as completed by vincelwt** 2018-03-07 21:43 UTC
