### ISSUE TITLE
Latest soundcloud likes missing

### ISSUE THREAD

**Issue by DLMousey** [vincelwt/harmony#191] opened 2017-10-17 15:49 UTC
This issue has cropped up in the last week or so, New tracks i `like` (monospace to emphasise the verb) on soundcloud aren't appearing in Harmony when the library is refreshed. Cleared preferences and cache a few times but doesn't seem to be helping. 

- **OS:** Windows 10 (10.0.15063)
- **Harmony Version:** 0.7.2 (Could it be worth displaying this in the options panel so we don't have to open the console and hope it's been logged there?)
- **Installed Plugins:** Soundcloud & Spotify (Have tried with Spotify disabled, Both are authenticated via Facebook)

No errors are showing in network panel or in console, Grabbed a screenshot comparing my Soundcloud likes to harmony's. (Browser is latest chrome, Cropped for privacy)

![image](https://user-images.githubusercontent.com/8281699/31674363-8e2ca5b8-b359-11e7-89e1-76bb99c1175c.png)

_(I'm on a serious Vicetone kick at the minute)_

**Comment by DLMousey** [comment] 2017-10-18 08:35
Ah good catch! Added a couple from Rameses B and Nightcore, They both worked fine first time, It never occured to me it might be something to do with the artist actually.

There's another one in there that seems to be missing as well - `Slow magic - Waited for you` from `thissongissick.com`, Could there be something on their accounts that's stopping them coming through in Harmony?

I thought it might have something to do with whether i follow that account on soundcloud but that doesn't seem to be the case, Tried following Vicetone, Clearing cache and refreshing library but it didn't seem to change anything.

Could the artist have some form of privacy control that restricts what goes out to the API from their uploads?

**Comment by vincelwt** [comment] 2017-11-02 14:28
Sorry for the late answer, I'm quite busy these days 

Thanks for the detailed investigation :)
Yep, some tracks are restricted through the API, but I've not yet seen an artist with all its tracks restricted.

Let me check on my side if I can reproduce and find the cause!

**Comment by vincelwt** [comment] 2017-11-03 10:30
So the tracks aren't returned at all by the API, which almost certainly means that the artist/right holders disabled their API access. 

For more details: https://stackoverflow.com/a/36529330

`SoundCloud emailed back saying they have introduced an option for right holders to disable all API access to tracks by default, returning this 403 error when requested. They also said it's understandable that this is a confusing feature, and that they hope to make it more clear.`

I don't think there is anything we can do, so I'll close this for now until further development of the situation by SoundCloud. Sorry :/

**Closed by vincelwt** 2017-11-03 10:30 UTC
