### ISSUE TITLE
When trying to play a Spotify playlist or song, it asks to install "the YouTube plugin"

### ISSUE THREAD

**Issue by bierlingm** [vincelwt/harmony#183] opened 2017-08-22 06:09 UTC
When I try to play a song or a playlist from Spotify, Harmony does not play it. Instead it displays the following message:

![screen shot 2017-08-22 at 08 04 47](https://user-images.githubusercontent.com/9335771/29550964-d55930ca-8710-11e7-8e89-7117a1166adf.png)

Funny thing is, I have given it access to my YouTube account. Is there a plugin I need to download? And if so, where do I find it?

**Comment by vincelwt** [comment] 2017-08-22 16:56
Hi, seems like a bug! C
Could you reproduce the error and send the log ? It is available by doing Cmd+Alt+I then console tab.

Then, could you enter in the console `console.log(services)` and report the result. ?

**Comment by Xilixir** [comment] 2017-08-29 17:20
I'm having this issue, too.

https://pastebin.com/raw/P8A0pCFs

**Comment by vincelwt** [comment] 2017-08-29 18:03
Thanks @Xilixir, this is a weird issue. Anyway it should be fixed with 0.8 as the youtube playing part as been totally rewritten.

**Comment by Xilixir** [comment] 2017-08-29 19:33
sweet, any ETA on the 0.8 release? I can't really use the program without spotify support :\

by the way, here's a spotify theme :) https://github.com/Xilixir/HarmonyDarker/blob/master/harmonydarker.css

**Comment by vincelwt** [comment] 2017-08-30 06:33
@Xilixir Hard to give an ETA, but I'd say between 1 and 3 weeks depending on how often I can work on it.
In the meantime maybe by resetting all the settings and reinstalling the app you could have some luck.

Congrats on the theme, I like it! Would it be ok to post it on the official repo [vincelwt/harmony-themes](https://github.com/vincelwt/harmony-themes) with credits to you ? That'd way we'd have an unified theme repo, and I'll add later on screenshots of each theme.

**Comment by Xilixir** [comment] 2017-08-31 01:09
Post it wherever, I don't need credit

**Comment by jjgh** [comment] 2017-09-18 14:24
I am on last version and I am experiencing the same problem.

**Comment by DLMousey** [comment] 2017-09-20 10:28
Been having the same issue intermittently in the last few weeks, A temporary workaround seems to be clearing cache & settings then re-authenticating with Spotify.

After doing this you usually have to close and re-open Harmony (also have to kill the process occasionally on Windows 10) before your library refreshes fully

**Comment by vincelwt** [comment] 2017-11-14 13:31
0.8 is out, and this issue should now be fixed :)

**Closed by vincelwt** 2017-11-14 13:31 UTC
Labels: bug

**Comment by maxxi-m** [comment] 2018-01-03 10:50
Hey, sorry for reviving this, I have not the same but a similiar issue. Whenever I want to play something on my spotify playlists harmony just searches for youtube videos and plays those instead. This is with version 0.82.

**Comment by vincelwt** [comment] 2018-01-03 12:27
@maxxi-m Hi, this is not a bug but the _expected_ behavior. Spotify doesn't let developers play tracks directly from them so we have to resort to others solutions, like playing from YouTube.

**Comment by maxxi-m** [comment] 2018-01-03 15:49
Oh ok, I wasn't aware of that sorry. Thanks!
